version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.staging
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - NODE_ENV=${NODE_ENV:-staging} #デフォはstaging
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - db
    command: ["sh", "-c", "if [ \"$NODE_ENV\" = \"staging\" ]; then npm run build && node dist/scripts/create-tables.js && node dist/server.js; else npm run build && node dist/server.js; fi"]

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
