version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
    - .env.staging
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - NODE_ENV=${NODE_ENV:-staging} #デフォはstaging
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - dynamodb
    command: ["sh", "-c", "if [ \"$NODE_ENV\" = \"staging\" ]; then npm run build && node dist/scripts/create-tables.js && node dist/server.js; else npm run build && node dist/server.js; fi"]

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/usr/src/app
    command: ["npm", "start"]
